### ISSUE TITLE
關於界面

### ISSUE THREAD

**Issue by wildskyf** [g0v/inviteyoself#5]
來問一下
為什麼 http://join.g0v.today/ 不是用 [shulusama/inviteyoself-g0v](https://github.com/shulusama/inviteyoself-g0v) 的設計呀~~
我覺得這個設計蠻好看的呀 :crying_cat_face:

![Preview](https://cloud.githubusercontent.com/assets/6042803/10990670/a880fecc-8490-11e5-8956-85a97664bda5.png)

**Comment by wildskyf** [comment]
ping @yhsiang

**Comment by yhsiang** [comment]
因為已經換成另一個 http://rauchg.com/slackin/
